### ISSUE TITLE
emg_hand_gestures.py

### ISSUE THREAD

**Issue by Conjure12** [hyperdimensional-computing/torchhd#137]
emg_hand_gestures.py  runs incorrectly：'MAPTensor' object has no attribute 'mT'

**Comment by mikeheddes** [comment]
Hi, thank you for opening this issue. It appears that [`torch.Tensor.mT`](https://pytorch.org/docs/1.11/tensors.html#torch.Tensor.mT) got introduced in PyTorch version 1.11.0. Please try upgrading your PyTorch version, if possible. 

I will see if we have to increase our minimum PyTorch version, or refactor the code to use older PyTorch operations.
