### ISSUE TITLE
`randsel` has inverted probability for input versus other selection

### ISSUE THREAD

**Issue by arendsee** [hyperdimensional-computing/torchhd#161]
The function `randsel` takes a parameter `p` which the documentation states is the probability of selecting a value from the `input` vector. So it should be true that `randsel(x, y, p=1) == x`. However, this is not true and instead `randsel(x, y, p=0) == x` and `randsel(x, y, p=1) == y`. 

`p` is the probability of **not** selecting from the `input` vector. I suspect you have a `1-p` in your code where you should just have `p`.

**Comment by mikeheddes** [comment]
Thank you for opening this issue. You are right, there is a `1-p` which shouldn't be. I will fix it right away.

**Comment by arendsee** [comment]
You could also just change the documentation. I'm using `randsel` to "fuzz" a vector. For example, `randsel(red_color, random(1, d), p=0.1)`, randomly moves 1/10 of the bits in `red_color`, making a "reddish" value. As it stands,`p` is a measure of the degree to which the input is moved toward the output.

**Comment by mikeheddes** [comment]
That would also be an option but with the changes I just made the API works the same as `torch.where` where `True` selects `input` and `False` selects other.
