### ISSUE TITLE
Define IMG_SIZE and BATCH_SIZE

### ISSUE THREAD

**Issue by MeatAcorn** [hyperdimensional-computing/torchhd#167]
Tutorial HDC Learning does not work, missing definitions for variables BATCH_SIZE and IMG_SIZE and all uppercase variables like DIMENSIONS.

**Comment by mikeheddes** [comment]
Thanks for opening this issue, please take a look at the [`/examples`](https://github.com/hyperdimensional-computing/torchhd/tree/main/examples) folder for working code. The tutorial is there for educational reasons and contains snippets of annotated code. That said, it would be good if the tutorial has working code.

**Comment by MeatAcorn** [comment]
Definitely, I was able to continue from the repository, just that the readthedocs example doesn't work as presented. Good stuff though, thanks for building it.

Sent from ProtonMail mobile

-------- Original Message --------
