### ISSUE TITLE
good  paper: Generalized Holographic Reduced Representations (GHRR), an extension of Fourier Holographic Reduced Representations (FHRR),

### ISSUE THREAD

**Issue by zdx3578** [hyperdimensional-computing/torchhd#170]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11037243/ Hyperdimensional computing with holographic and adaptive encoder

https://arxiv.org/abs/2405.09689
Generalized Holographic Reduced Representations 
Calvin Yeung, Zhuowen Zou, Mohsen Imani Deep learning has achieved remarkable success in recent years. Central to its success is its ability to learn representations that preserve task-relevant structure. However, massive energy, compute, and data costs are required to learn general representations. This paper explores Hyperdimensional Computing (HDC), a computationally and data-efficient brain-inspired alternative. HDC acts as a bridge between connectionist and symbolic approaches to artificial intelligence (AI), allowing explicit specification of representational structure as in symbolic approaches while retaining the flexibility of connectionist approaches. However, HDC's simplicity poses challenges for encoding complex compositional structures, especially in its binding operation. To address this, we propose Generalized Holographic Reduced Representations (GHRR), an extension of Fourier Holographic Reduced Representations (FHRR), a specific HDC implementation. GHRR introduces a flexible, non-commutative binding operation, enabling improved encoding of complex data structures while preserving HDC's desirable properties of robustness and transparency. In this work, we introduce the GHRR framework, prove its theoretical properties and its adherence to HDC properties, explore its kernel and binding characteristics, and perform empirical experiments showcasing its flexible non-commutativity, enhanced decoding accuracy for compositional structures, and improved memorization capacity compared to FHRR. Subjects:	Machine Learning (cs.LG); Artificial Intelligence (cs.AI); Symbolic Computation (cs.SC) Cite as:	
arXiv:2405.09689

**Comment by mikeheddes** [comment]
Hi, thank you for opening this issue. Could you please provide more information on why you created this issue?

**Comment by zdx3578** [comment]
something good；

https://github.com/MAGICS-LAB/UHop ： Uniform Memory Retrieval with Larger Capacity for Modern Hopfield Models.

**Comment by mikeheddes** [comment]
Thank you for sharing these works, they are indeed interesting. Could you please provide more information on your intentions by creating this issue?

**Comment by zdx3578** [comment]
VSA use in. https://github.com/IBM/learn-vector-symbolic-architectures-rule-formulations  https://github.com/IBM/neuro-vector-symbolic-architectures-raven  get good result in RAVEN test, but i implement is manual , if use torchhd can more expandability？ and https://arcprize.org/  test like RAVEN，maybe VSA is helpful?
