### ISSUE TITLE
Experiment with different implementations and their speeds

### ISSUE THREAD

**Issue by mikeheddes** [hyperdimensional-computing/torchhd#26]
For example the `functional.ngrams` function can be implemented in a number of ways, we should look into which way is the fasted both on CPU and GPU. The same goes for other functions, classes and loading of datasets.

**Comment by aglinxinyuan** [comment]
What's the bigram for torch.tensor([[1,2,3,4,5,6]])?

**Comment by mikeheddes** [comment]
If you only pass it one hypervector there are no bigrams. If you had a tensor T of 3 by d with 3 hypervectors of d dimensions then it would be  T[0]*P(T[1]) +T[1]*P(T[2]) where P is permutation. Hope this helps

**Comment by aglinxinyuan** [comment]
Are the `distinct_sequence` and the `ngrams` doing the same thing?
For the tensor `torch.randint(-1, 2, (100,3,10000))`, unbind approach is slower than the for loop approach on both CPU and GPU.

CPU:
`ngrams: 8.08 ms ± 62.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`
`distinct_sequence: 9.65 ms ± 101 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`

GPU:
`ngrams: 324 µs ± 5.16 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)`
`distinct_sequence: 357 µs ± 6.74 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)`

**Comment by mikeheddes** [comment]
No a distinct sequence implements a binding-based sequence where for the same 3 element tensor T the result should be: P(P(T[0])) * P(T[1]) * T[2]. Here all the elements are permuted by a decreasing amount such that the last element is not permuted and all the permuted hypervectors are bound together instead of bundled.

**Comment by aglinxinyuan** [comment]
Can you give me an tensor that `distinct_sequence()` and `ngrams()` return different results? I understand that the formulas of those two functions are different, but they always return the same results when I test them with different shapes.

**Comment by mikeheddes** [comment]
Here's an example:
```python
>>> from torchhd import functional
>>> x = functional.random_hv(10, 1000)
>>> ngrams = functional.ngrams(x)
>>> distinct_sequence = functional.distinct_sequence(x)
>>> ngrams == distinct_sequence
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
```

**Comment by aglinxinyuan** [comment]
They will still return the same result if I changed n to 10: `ngrams = functional.ngrams(x,n=10)`

**Comment by mikeheddes** [comment]
Yes, that is correct. The ngrams are like an interpolation between binding-based sequences (distinct sequence) and a multiset. If you set n to the size of the input sequence there is no difference with the distinct sequence because there is only one ngram of that size.

**Comment by aglinxinyuan** [comment]
I tried more than ten approaches: unbind, for-loop, select, index_select, strided, in-place, out-of-place, and gather.
In-place for-loop is significantly faster than the others. 
The same approach #33 can be applied to `distinct_sequence()` and `sequence()` after verification.

**Comment by aglinxinyuan** [comment]
Update on PyTorch C++ extension: it requires the user to install a C++ compiler which is easy for Linux users (just one command) but hard for windows users(need to download a large installer package manually and config it manually). So we stay away from c++ to make it easy to use for Windows users.

**Comment by mikeheddes** [comment]
Thank you for the update. I agree, I don't think we have the expertise yet to pull off such a project.
