### ISSUE TITLE
Add plotting

### ISSUE THREAD

**Issue by mikeheddes** [hyperdimensional-computing/torchhd#8]
Add two utility functions that will generate a similarity plot. There first one gets the similarity characteristics of a basis hypervector set. The second shows the similarity of one hypervector with a set.

- [ ] Set characteristics
- [ ] Hypervector with set similarities

**Comment by dheyay** [comment]
The hypervectors with set similarity should be able to take a vector and a set?
Or in line with the fruit example, we take the vector and set(s), bind together and find similarity with all sets(memory) ?

**Comment by mikeheddes** [comment]
For the hypervector with set you just plot the similarity of one hypervector with a set of hypervectors, like this:
```python
memory = torchhd.random_hv(8, 10000)
similarity = torchhd.functional.cosine_similarity(memory[0], memory)
# plot the similarity with matplotlib using the stem
```

Docs: [`plt.stem`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.stem.html)
